theme: minima
plugins:
- jekyll-remote-theme

# cayman is for stakingpower
# remote_theme: pages-themes/cayman@v0.2.0

# hacker is for moonode
# remote_theme: pages-themes/hacker@v0.2.0

# modernist is for mohismstake
# remote_theme: pages-themes/modernist@v0.2.0

